"""
Media generation routes:
  POST /media/generate/image        — Generate image from chat context
  POST /media/generate/video        — Start async video generation
  GET  /media/jobs/{job_id}         — Poll video job status
  GET  /media/{media_id}            — Get media metadata
  GET  /media/user                  — List all user media
"""
import uuid

from fastapi import APIRouter, BackgroundTasks, HTTPException, Request, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.dependencies import DB, AppSettings, CurrentUser
from app.models.media import GeneratedMedia, JobStatus, MediaJob, MediaStatus, MediaType
from app.schemas.media import (
    ImageGenerateRequest,
    ImageGenerateResponse,
    JobStatusResponse,
    MediaListResponse,
    MediaOut,
    VideoGenerateRequest,
    VideoGenerateResponse,
)
from app.services.media_service import MediaService

router = APIRouter()


@router.post(
    "/generate/image",
    response_model=ImageGenerateResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Generate image from current chat session context",
)
async def generate_image(
    body: ImageGenerateRequest,
    request: Request,
    current_user: CurrentUser,
    db: DB,
    settings: AppSettings,
):
    """
    Summarizes the chat session to create an image prompt,
    then calls Cloudflare Workers AI (SDXL) to generate the image.
    Image is saved to media/ and a GeneratedMedia record is created.
    """
    inference_client = request.app.state.inference_client
    service = MediaService(db, settings, inference_client)
    return await service.generate_image(body.session_id, body.message_id, current_user)


@router.post(
    "/generate/video",
    response_model=VideoGenerateResponse,
    status_code=status.HTTP_202_ACCEPTED,
    summary="Start async video generation from chat session",
)
async def generate_video(
    body: VideoGenerateRequest,
    background_tasks: BackgroundTasks,
    request: Request,
    current_user: CurrentUser,
    db: DB,
    settings: AppSettings,
):
    """
    Kicks off the async video pipeline:
    chat → narration script → Edge-TTS audio → Islamic slide → FFmpeg MP4.
    Returns a job_id to poll for status.
    """
    inference_client = request.app.state.inference_client
    session_maker = request.app.state.session_maker
    service = MediaService(db, settings, inference_client)
    return await service.start_video_job(body.session_id, body.message_id, current_user, background_tasks, session_maker)


@router.get(
    "/jobs/{job_id}",
    response_model=JobStatusResponse,
    summary="Poll video generation job status",
)
async def get_job_status(
    job_id: str,
    current_user: CurrentUser,
    db: DB,
    settings: AppSettings,
):
    """
    Poll the status of a video generation job.
    When status=completed, video_url is populated.
    """
    try:
        jid = uuid.UUID(job_id)
    except ValueError:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Job not found")

    # Load job + verify user owns the associated media
    result = await db.execute(
        select(MediaJob).where(MediaJob.id == jid)
    )
    job = result.scalar_one_or_none()
    if not job:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Job not found")

    # Verify ownership via media record
    media_result = await db.execute(
        select(GeneratedMedia).where(
            GeneratedMedia.id == job.media_id,
            GeneratedMedia.user_id == current_user.id,
        )
    )
    media = media_result.scalar_one_or_none()
    if not media:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Job not found")

    video_url = None
    if job.status == JobStatus.completed and media.file_path:
        video_url = f"{settings.media_base_url}/{media.file_path}"

    return JobStatusResponse(
        job_id=str(job.id),
        status=job.status.value,
        progress_pct=job.progress_pct,
        video_url=video_url,
        error=job.error_detail,
        started_at=job.started_at,
        completed_at=job.completed_at,
    )


@router.get(
    "/user",
    response_model=MediaListResponse,
    summary="List all media generated by current user",
)
async def list_user_media(
    current_user: CurrentUser,
    db: DB,
):
    """Returns all images and videos generated by the current user."""
    result = await db.execute(
        select(GeneratedMedia)
        .where(GeneratedMedia.user_id == current_user.id)
        .order_by(GeneratedMedia.created_at.desc())
    )
    media_list = result.scalars().all()
    items = [_media_out(m) for m in media_list]
    return MediaListResponse(media=items, total=len(items))


@router.get(
    "/{media_id}",
    response_model=MediaOut,
    summary="Get metadata for a specific media item",
)
async def get_media(
    media_id: str,
    current_user: CurrentUser,
    db: DB,
):
    """Returns metadata for a specific generated media item owned by current user."""
    try:
        mid = uuid.UUID(media_id)
    except ValueError:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Media not found")

    result = await db.execute(
        select(GeneratedMedia).where(
            GeneratedMedia.id == mid,
            GeneratedMedia.user_id == current_user.id,
        )
    )
    media = result.scalar_one_or_none()
    if not media:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Media not found")
    return _media_out(media)


# ─── Helpers ─────────────────────────────────────────────────────────────────

def _media_out(media: GeneratedMedia) -> MediaOut:
    return MediaOut(
        id=str(media.id),
        media_type=media.media_type.value,
        file_path=media.file_path,
        prompt_used=media.prompt_used,
        status=media.status.value,
        created_at=media.created_at,
        completed_at=media.completed_at,
    )
